accent = "#9FEF00"
cursor = "#A4B1CD"
foreground = "#A4B1CD"
background = "#141D2B"
selection_foreground = "#141D2B"
selection_background = "#9FEF00"

color0 = "#1A2332"
color1 = "#FF8484"
color2 = "#9FEF00"
color3 = "#FFCC5C"
color4 = "#5CB2FF"
color5 = "#CF8DFB"
color6 = "#5CECC6"
color7 = "#A4B1CD"
color8 = "#3D5A80"
color9 = "#FFA0A0"
color10 = "#C5F467"
color11 = "#FFD980"
color12 = "#7FC4FF"
color13 = "#DCB0FC"
color14 = "#90F4D8"
color15 = "#C5D1EB"
